export const state = [
  {
    id: 1,
    genre: "Asssss",
    author: "Оноре де'Пардикат ",
    copy: [
      { id: 0, totalId: 1, currentUser: "" },
      { id: 0, totalId: 1, currentUser: "" },
    ],
    name: "Ну сука оооочень дльнннннннное ннннннназваннниееееее",
    age: 2018,
    publishHouse: "Red Army",
    description: "",
  },
  {
    id: 2,
    genre: "asynfcnbrf",
    author: "Rene2 ",
    copy: [{ id: 0, totalId: 2, currentUser: "" }],
    name: "QWER2",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.2222222222222222",
  },
  {
    id: 3,
    genre: "hjvfy",
    author: "Rene3 ",
    copy: [{ id: 0, totalId: 3, currentUser: "" }],
    name: "QWER3",
    age: 2018,
    publishHouse: "Red Army",
    description: "",
  },
  {
    id: 4,
    genre: ",jtdbr",
    author: "Rene4 ",
    copy: [{ id: 0, totalId: 4, currentUser: "" }],
    name: "QWER4",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.4444444444444444",
  },
  {
    id: 5,
    genre: "ewdrvdfgg",
    author: "Rene5 ",
    copy: [{ id: 0, totalId: 5, currentUser: "" }],
    name: "QWER5",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore 55555555555555.",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
  {
    id: 6,
    genre: "wirignbng",
    author: "Rene6 ",
    copy: [{ id: 0, totalId: 6, currentUser: "" }],
    name: "QWER6",
    age: 2018,
    publishHouse: "Red Army",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, nam nostrum. Delectus, quae numquam cum nostrum veritatis illum laboriosam accusamus esse magni doloribus temporibus nesciunt, impedit corporis repudiandae, neque dolore.6666666666666",
  },
]

export const users = [
  {
    id: 25,
    name: "Serg",
    surname: "Romanenko",
    phone: "09",
    history: [],
    use: [],
    rate: 0,
  },
  {
    id: 26,
    name: "Serg1",
    surname: "Romanenko1",
    phone: "0972",
    history: [],
    use: [],
    rate: 0,
  },
  {
    id: 27,
    name: "Serg2",
    surname: "Romanenko2",
    phone: "097298",
    history: [],
    use: [],
    rate: 0,
  },
  {
    id: 28,
    name: "Serg3",
    surname: "Romanenko3",
    phone: "0972987",
    history: [],
    use: [],
    rate: 0,
  },
  {
    id: 29,
    name: "Serg4",
    surname: "Romanenko4",
    phone: "0972987314",
    history: [],
    use: [],
    rate: 0,
  },
]
